name: Checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  powershell-5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run deployment state tests
        shell: powershell
        run: powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File .\tests\run-tests.ps1
